### ISSUE TITLE
Suggestion for ReadMe: Explanation of What an OpenAI specification Is

### ISSUE THREAD

**Issue by VikR1000** [AndrewWalsh/openapi-devtools#1]
Suggested improvement to the ReadMe: add a paragraph explaining what an OpenAI specification is.  I just read this:

https://swagger.io/specification/

...and I'm not quite sure yet what it is or where it is used.

I've used OpenAI a lot through its UI but not via code yet. :)

**Comment by veilm** [comment]
OpenAPI != OpenAI

**Comment by VikR1000** [comment]
Ohhhh... okay, thanks. At the same time, a paragraph describing OpenAPI and its use cases would be helpful.

**Comment by AndrewWalsh** [comment]
I think that would be useful @VikR1000. I will expand the README with a short description about that, thank you.

Edit: added a very short explanation to point newcomers in the right direction.
