### ISSUE TITLE
Bug: OpenAPI tab not showing in google chrome.

### ISSUE THREAD

**Issue by TylerCode** [AndrewWalsh/openapi-devtools#10]
On Windows 11 running Chrome Version 119.0.6045.106 (Official Build) (64-bit)

This could be a misunderstanding on my part but my assumption is that post install, it would show either in this list. 

![image](https://github.com/AndrewWalsh/openapi-devtools/assets/18288340/b27527d2-f2eb-4bb0-b59c-37fc42f12e8f)

or in this list

![image](https://github.com/AndrewWalsh/openapi-devtools/assets/18288340/31cd2163-c6f2-4769-b1aa-50ddd634b9d7)

If there is something more to do in order to get it to show up it might be worth putting in the readme.

**Comment by dword4** [comment]
I am also seeing this in both Windows and MacOS, updated Chrome, reinstalled the extension and still nothing.

**Comment by TylerCode** [comment]
Okay, glad I'm not crazy. Thought I must have missed something since it's the first time I've used the extension. 

If there is a way to get debugging information, let me know and I'll post it here.

**Comment by AndrewWalsh** [comment]
@TylerCode @dword4 Thanks for raising this, it's not just you, it's broken for everybody. It's a very small thing, but has broken the Chrome build. The fix is in v1.3.2, will roll this out soon.

**Comment by TylerCode** [comment]
Do you know when this will go out to the chrome store? If it will be a bit I'm cool installing it manually, just don't want to do it for the store to update the next day :D

**Comment by dword4** [comment]
I have no clue, never dealt with the store beyond just clicking install

**Comment by TylerCode** [comment]
Sorry @dword4 , meant to tag @AndrewWalsh

**Comment by AndrewWalsh** [comment]
It shouldn't be long. I uploaded this more than 24hrs ago. I've tracked it myself, it's taking a while. I trust it will be out soon. @TylerCode.

**Comment by TylerCode** [comment]
Thanks for the update, sorry for being that guy.

**Comment by AndrewWalsh** [comment]
You're not that guy @TylerCode, thanks for reporting this. I can only wait until the Chrome team release the update I've posted, but I appreciate the report.

**Comment by AndrewWalsh** [comment]
v1.3.2 has been released in the Chrome Web Store, thanks again @TylerCode.

**Comment by TylerCode** [comment]
Thanks again for getting this out, used it yesterday to help with some ambiguity on the Discuit API. Great tool.

Tested on Chrome in Windows 11 and on Brave in Arch.

**Comment by AndrewWalsh** [comment]
@TylerCode That's awesome, great to hear that this is useful for yourself and others 👍 .
