### ISSUE TITLE
Feature request: add integration and prompt for ChatGPT to generate descriptions of fields, models, methods 

### ISSUE THREAD

**Issue by MarshalX** [AndrewWalsh/openapi-devtools#2]

**Comment by AndrewWalsh** [comment]
If you want to do something like that, you could try creating a tool to parse the spec and make additions to it. Otherwise, this is out of scope.

**Comment by AndrewWalsh** [comment]
@MarshalX @hoosnick You can now give this a shot with https://github.com/Superflows-AI/openapi-llm

**Comment by MarshalX** [comment]
@AndrewWalsh thank you!
