### ISSUE TITLE
Path parameters with colons not OpenAPI 3.1 compliant?

### ISSUE THREAD

**Issue by elrubio** [AndrewWalsh/openapi-devtools#21]
First off, thanks a lot for this super-useful tool! 🙏🏼

When I passed my generated spec file to my code generator, it complained about invalid path parameters containing colons. 

Indeed, the [OpenAPI specs](https://spec.openapis.org/oas/latest.html#path-templating) only seem to allow curly braces and don't mention colons: 

> 3.2 Path Templating
> 
> Path templating refers to the usage of template expressions, delimited by **curly braces ({})**, to mark a section of a URL path as replaceable using path parameters.
> 

After changing my spec file accordingly, code generation worked.

Is there a specific reason your generated documents deviate from the OpenAPI spec? Could this be changed to meet the standard?

**Comment by AndrewWalsh** [comment]
Thanks @elrubio, that's definitely a bug, I kind of hacked this together.

I will address this along with the other PR next week.

**Comment by AndrewWalsh** [comment]
I have in mind a CLI tool now to supercede this to autogenerate OpenAPI 3.1 or 4.0 specifications for any API, so I'm not looking to improve this approach further unless there is significant demand, apologies!

**Comment by AndrewWalsh** [comment]
@elrubio Please see the new version https://github.com/AndrewWalsh/demystify
