### ISSUE TITLE
Record auth headers

### ISSUE THREAD

**Issue by gibbiemonster** [AndrewWalsh/openapi-devtools#3]
Awesome work! I have one feature request though - could it record auth headers/tokens? This would be super useful for logging which requests require authorization and how to send an authorized request

**Comment by AndrewWalsh** [comment]
Thank you! Agreed this would be great to have, I'll take a look at implementing this.

**Comment by AndrewWalsh** [comment]
This is now in version v1.3.0.

**Comment by gibbiemonster** [comment]
Thanks!

**Comment by TylerCode** [comment]
Perfect timing! I was just about to give this a go, legend!
