### ISSUE TITLE
Running on the background

### ISSUE THREAD

**Issue by fernandosmither** [AndrewWalsh/openapi-devtools#4]
Excellent tool, congrats for hn # 1!

Would it be possible to opt-in always running the extension on the background, so that you don't need to worry about profiling a specific website, and just passively collect all API's you've accessed?

Might be relevant when you've lost access to a front (or if the front gets taken down) and you'd like to directly communicate with the API.

**Comment by AndrewWalsh** [comment]
Thank you! This makes use of the `chrome.devtools.network` API which is only available when Chrome DevTools is open. This isn't possible with the approach this tool takes. There is a tool that could achieve that (I think) though called [Akita](https://chrome.google.com/webstore/detail/akita-openapi-spec-genera/liiefniacemgfkiahaialiganopbdngn).
