### ISSUE TITLE
Request: Firefox extension

### ISSUE THREAD

**Issue by juxuanu** [AndrewWalsh/openapi-devtools#5]
It would be awesome to have this in Firefox as well :-)

**Comment by AndrewWalsh** [comment]
Someone has raised the prospect of working on it, so you may see that soon.

https://news.ycombinator.com/item?id=38012032

**Comment by ghostsquad** [comment]
Came here just for this issue.

**Comment by jpvajda** [comment]
I'm definitely looking forward to the FF version of this. 🦊

**Comment by TylerCode** [comment]
Throwing some support into a FF version.

**Comment by madeindjs** [comment]
Just tried to build locally the extension and then load he application unpackaked on Firefox 124 and it works fine

**Comment by AndrewWalsh** [comment]
@madeindjs That's great. I know a lot more about browser extensions now than I did when I created this tool. Could you share the manifest, build command, and other relevant details you're using? If so, I can create two build outputs and submit this to Firefox. Otherwise, I'll take a look at this next week.

**Comment by madeindjs** [comment]
@AndrewWalsh , I just opened a PR using [`web-ext`](https://github.com/mozilla/web-ext) to pack / test the extension on Firefox and Chromium.

Honestly, I'm not very familar about browser extensions, I just discovered `web-ext` and suprisingly, it works as is :shrug: .

**Comment by AndrewWalsh** [comment]
@madeindjs Perfect, I've merged this now. Thanks for the PR, I'll get this published to Firefox later today.

**Comment by AndrewWalsh** [comment]
@madeindjs I've submitted this to Firefox. Once it's available I'll update the readme and publish a new release, thanks again.

**Comment by madeindjs** [comment]
Thank your for merging the PR and publish it for Firefox ❤️

**Comment by AndrewWalsh** [comment]
This is now available at https://addons.mozilla.org/en-US/firefox/addon/openapi-devtools/. I'll create a new release shortly. The use of `web-ext` was a great call, much slicker than the old approach.

**Comment by juxuanu** [comment]
Working well, thanks!
