### ISSUE TITLE
Feature request: Optionally collect sample values for each field in a JSON API

### ISSUE THREAD

**Issue by stevennyman** [AndrewWalsh/openapi-devtools#7]
It would be helpful to see what some possible values would be for each key in a JSON API instead of only the type of the value.

**Comment by AndrewWalsh** [comment]
Nice suggestion, as an opt-in only feature this could work. I've avoided it as I don't want there to be any possibility of people downloading specs that contain sensitive data like PII. It's too easy to make a mistake on that end, but I will track this.

**Comment by demerzel21** [comment]
Same idea - it would be particularly good for lookup tables, to see sample values.

**Comment by richpinky007** [comment]
yes look up tables to see sample values

**Comment by AndrewWalsh** [comment]
This is now in release v1.2.0.
