### ISSUE TITLE
Feature Request: Session Continuation and OpenAPI Specification Import

### ISSUE THREAD

**Issue by colin6-work** [AndrewWalsh/openapi-devtools#9]
Currently, closing the browser results in a loss of the generated OpenAPI specification data. To enhance usability and continuity, could we consider the following features?

1. Implementing a session save feature that allows users to pause and resume their recording sessions at a later time.

2. Providing an option to upload a JSON file of a previously downloaded OpenAPI specification, enabling users to continue recording from where they left off.

**Comment by AndrewWalsh** [comment]
Great suggestion @colin6-work, I have things set up to make this possible. I'll implement this in the next version.

**Comment by AndrewWalsh** [comment]
This is now in release v1.2.0.
